name: Update Formula

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to update to (e.g. v0.1.2)'
        required: true
        type: string

env:
  FORMULA_NAME: spotter

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Update formula
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
        run: |
          # Get SHA256 hashes from release files
          MACOS_SHA256=$(curl -sL "https://github.com/kohbis/${{ env.FORMULA_NAME }}/releases/download/${VERSION}/${{ env.FORMULA_NAME }}-macos.sha256")
          LINUX_SHA256=$(curl -sL "https://github.com/kohbis/${{ env.FORMULA_NAME }}/releases/download/${VERSION}/${{ env.FORMULA_NAME }}-linux.sha256")
          
          # Update formula file
          sed -i "s/version \".*\"/version \"${VERSION}\"/" Formula/${{ env.FORMULA_NAME }}.rb
          sed -i "s/sha256 \".*\" # macos/sha256 \"${MACOS_SHA256}\" # macos/" Formula/${{ env.FORMULA_NAME }}.rb
          sed -i "s/sha256 \".*\" # linux/sha256 \"${LINUX_SHA256}\" # linux/" Formula/${{ env.FORMULA_NAME }}.rb
          
          # Create branch and commit
          git checkout -b update-formula-${VERSION}
          git add Formula/${{ env.FORMULA_NAME }}.rb
          git commit -m "Update formula to ${VERSION}"
          git push origin update-formula-${VERSION}

          # Create PR
          gh pr create \
            --base main \
            --title "Update formula to ${VERSION}" \
            --body "This PR updates the formula to version ${VERSION}."
